# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
darklua = "seaofvoices/darklua@0.10.2"
rojo = "rojo-rbx/rojo@7.4.0-rc3"
tarmac = "rojo-rbx/tarmac@0.7.4"